name: Build and Deploy

# Triggers the workflow whenever you push commits to the main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Here we have a single job called 'firebase-deploy'
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Refer to repos in https://github.com/actions for more
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      # Set up the environment variables for the app
      - name: Create Environment directory
        run: mkdir -p ./src/environments
      - name: Create Environment file
        run: |
          echo "export const environment = {" >> ./src/environments/environment.ts
          echo "  production: true," >> ./src/environments/environment.ts
          echo "  backendURL: '${{ secrets.BACKEND_URL }}'," >> ./src/environments/environment.ts
          echo "  imgBBurl: '${{ secrets.IMGBB_URL }}'," >> ./src/environments/environment.ts
          echo "  baseURL: '${{ secrets.BASE_URL }}'" >> ./src/environments/environment.ts
          echo "};" >> ./src/environments/environment.ts
      # Install node modules that need to build the app. Then build the app using prod env vars.
      - run: npm install
      - run: npm run build:prod
      # Deploy the app artifact to firebase
      - uses: w9jds/firebase-action@v4
        with:
          args: deploy --only hosting
        env:
          # Here we use the actions secret we set earlier
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
