name: CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Create Environment file
        run: |
          echo "export const environment = {" >> ./src/environments/environment.ts
          echo "  production: true," >> ./src/environments/environment.ts
          echo "  backendURL: '${{ secrets.BACKEND_URL }}'," >> ./src/environments/environment.ts
          echo "  imgBBurl: '${{ secrets.IMGBB_URL }}'," >> ./src/environments/environment.ts
          echo "  baseURL: '${{ secrets.BASE_URL }}'" >> ./src/environments/environment.ts
          echo "};" >> ./src/environments/environment.ts
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build --prod
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/portfolio

  deploy:
    name: Deploy to firebase
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist
      - name: Deploy angular app to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
          channelId: live
          projectId: portfolio-99e5b
